#!/bin/sh
set -e

echo "Compile"

mkdir -p target/classes target/test-classes

CLASSPATH=target/classes:target/test-classes
JARFILE=
for JARFILE in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$JARFILE
done

javac -d target/classes -classpath $CLASSPATH src/main/java/com/baldurtech/scaling/octo/ironman/*.java
javac -d target/test-classes -classpath $CLASSPATH src/test/java/com/baldurtech/scaling/octo/ironman/*.java
