#!/bin/sh

test -z "$CATALINA_HOME" && echo "CATALINA_HOME not set." && exit 1

rm -r -f $CATALINA_HOME/webapps/member

cp -r src/main/webapp $CATALINA_HOME/webapps/member
cp -r target/classes $CATALINA_HOME/webapps/member/WEB-INF/

cp -r lib $CATALINA_HOME/webapps/member/WEB-INF/
rm $CATALINA_HOME/webapps/member/WEB-INF/lib/servlet-api.jar
