#!/bin/sh

echo "Run test"

CLASSPATH=target/classes:target/test-classes

for JARFILE in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$JARFILE
done

java -classpath $CLASSPATH com.baldurtech.unit.MiniatureSpiceTestCase com.baldurtech.scaling.octo.ironman
