#!/bin/sh

echo "Run test"

CLASSPATH=lib/reflections-0.9.9-RC2.jar:lib/servlet-api.jar:lib/mockito-all-1.9.5.jar:target/classes:target/test-classes
CLASSPATH=$CLASSPATH:~/miniature-spice-unit-test.jar
CLASSPATH=$CLASSPATH:~/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar
CLASSPATH=$CLASSPATH:~/.m2/repository/org/javassist/javassist/3.18.2-GA/javassist-3.18.2-GA.jar

java -classpath $CLASSPATH com.baldurtech.unit.MiniatureSpiceTestCase com.baldurtech.scaling.octo.ironman
